name: FarmMC
version: '${project.version}'
main: tokyo.ramune.farmmc.FarmMC
api-version: 1.19

depend:
  - PlugMan

commands:
  farmmc:
    description: "FarmMC"
    aliases:
      - "farm"
    permission: FarmMC.command
    permission-message: "You fool"