name: FarmMC
version: '${project.version}'
main: tokyo.ramune.farmmc.FarmMC
api-version: 1.19

depend:
  - PlugMan

commands:
  farmmc:
    description: "FarmMC"
    aliases:
      - "farm"
    permission: FarmMC.command
    permission-message: "You fool"

permissions:
  FarmMC.command:
    default: true
  FarmMC.command.help:
    default: true
  FarmMC.command.language:
    default: true
  FarmMC.command.setting:
    default: true
  FarmMC.command.maintenance:
    default: op
  FarmMC.command.reload:
    default: op
  FarmMC.command.spawn:
    default: op
  FarmMC.command.force-spawn:
    default: op
  FarmMC.command.sql-query:
    default: op

  join.maintenance:
    default: op