name: FarmMC
version: '${project.version}'
main: tokyo.ramune.farmmc.FarmMC
api-version: 1.19

depend:
  - PlugMan

commands:
  farmmc:
    description: "FarmMC"

permissions:
  FarmMC:
    command:
      help:
        default: true
      language:
        default: true
      maintenance:
        default: op
      reload:
        default: op
      spawn:
        default: op
      force-spawn:
        default: op
    join:
      maintenance:
        default: op